# Utilisation de l'image officielle de Node.js
FROM node:16

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code source dans le conteneur
COPY . .

# Exposer le port de l'application (ici le port 3000 ou autre si nécessaire)
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["npm", "start"]
